# will match all of them
Default:
  action: main::index

Log: 
  route: log/:page
  action: main::log
  params:
    page: \d+ 1

Manage:
  route: zarzadzaj
  action: main::manage

Edit Plan:
  route: plan/:id/edit
  action: main::planEdit

Plan Costs Form:
  route: plan/:id/cost/:date
  action: main::planCost
  params:
   id: \d+
   date: \d{4}-\d{2}-\d{2} yesterday
   
Report:
  route: raport
  action: main::getReport

Get BBelements Stats:
  route: bot/getBBelements/:date
  action: bot::getBbelements
  params:
    date: \d{4}-\d{2}-\d{2} yesterday
  
Get Meta Stats:
  route: bot/getMetaStats/:date
  action: bot::getmetalyzerstats
  params:
    date: \d{4}-\d{2}-\d{2} yesterday

Get Trade Doubler Stats:
  route: bot/getTradeDoubler/:date
  action: bot::gettradedoublerstats
  params:
    date: \d{4}-\d{2}-\d{2} yesterday 

